# Generated by Django 3.1.3 on 2021-01-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_count',
            name='key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
